# Generated by Django 5.0.2 on 2025-06-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landlordprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
