from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard_redirect, name='dashboard'),
    path('landlord/dashboard/', views.landlord_dashboard, name='landlord_dashboard'),
    path('tenant/dashboard/', views.tenant_dashboard, name='tenant_dashboard'),
    path('rooms/', views.room_list, name='room_list'),
    path('rooms/add/', views.room_add, name='room_add'),
    path('rooms/<int:room_id>/', views.room_detail, name='room_detail'),
    path('rooms/<int:room_id>/edit/', views.room_edit, name='room_edit'),
    path('rooms/<int:room_id>/delete/', views.room_delete, name='room_delete'),
    path('api/search/', views.search_api, name='search_api'),
    path('rooms/<int:room_id>/tenants/add/', views.roomtenant_add, name='roomtenant_add'),
    path('rooms/<int:room_id>/tenants/<int:assignment_id>/edit/', views.roomtenant_edit, name='roomtenant_edit'),
    path('rooms/<int:room_id>/tenants/<int:assignment_id>/archive/', views.roomtenant_archive, name='roomtenant_archive'),
    path('rooms/<int:room_id>/tenants/<int:assignment_id>/addons/', views.addon_add, name='addon_add'),
    path('rooms/<int:room_id>/tenants/<int:assignment_id>/addons/<int:addon_id>/delete/', views.addon_delete, name='addon_delete'),
    path('tenants/', views.tenant_list, name='tenant_list'),
    path('tenants/archived/', views.archived_tenants, name='archived_tenants'),
    path('tenants/<int:assignment_id>/restore/', views.roomtenant_restore, name='roomtenant_restore'),
    path('payments/', views.payment_list, name='payment_list'),
    path('payments/<int:payment_id>/edit/', views.payment_edit, name='payment_edit'),
    path('payments/tracking/', views.payment_tracking, name='payment_tracking'),
    path('payments/add/<int:tenant_id>/', views.add_payment, name='add_payment'),
    path('payments/history/', views.payment_history, name='payment_history'),
    path('receipts/<int:receipt_id>/download/', views.download_receipt, name='download_receipt'),
    path('landlord/signature/', views.manage_signature, name='manage_signature'),
    path('tenants/<int:tenant_id>/payments/', views.tenant_payment_history, name='tenant_payment_history'),
    path('tenants/create/', views.tenant_create, name='tenant_create'),
    path('account/force-password-change/', views.force_password_change, name='force_password_change'),
    path('tenant/rooms/', views.tenant_room_list, name='tenant_room_list'),
    path('tenant/rooms/<int:room_id>/', views.tenant_room_detail, name='tenant_room_detail'),
    path('tenant/payments/tracker/', views.tenant_payment_tracker, name='tenant_payment_tracker'),
] 